# Generated by Django 5.1.6 on 2025-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('items', models.CharField(max_length=500)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('в ожидании', 'в ожидании'), ('готов', 'готов'), ('оплачено', 'оплачено')], max_length=15)),
            ],
        ),
    ]
