# Generated by Django 5.1.6 on 2025-03-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('items', models.CharField(max_length=500)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('W', 'в ожидании'), ('R', 'готов'), ('P', 'оплачено')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_summ', models.PositiveIntegerField()),
            ],
        ),
    ]
